apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  # - path: _patches/vote.yaml
  - path: _patches/service.yaml

replicas:
- name: vote
  count: 1

images:
- name: schoolofdevops/vote
  newTag: v4

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported_by: flux_cert